import { Semester, Year } from "@/generated/prisma/enums";
import { Student, Teacher } from "@/types/index.types";

const genders = [
	{ label: "MALE", value: "MALE" },
	{ label: "FEMALE", value: "FEMALE" },
	{ label: "OTHER", value: "OTHER" },
] as const;
const departments = [
	{ label: "CIVIL", value: "CIVIL" },
	{ label: "CEIT", value: "CEIT" },
	{ label: "EC", value: "EC" },
	{ label: "MP", value: "MP" },
	{ label: "EP", value: "EP" },
] as const;
const roles = [
	{ label: "ADMIN", value: "ADMIN" },
	{ label: "HOD", value: "HOD" },
	{ label: "TEACHER", value: "TEACHER" },
] as const;
const Years = [
	{ label: "First Year", value: Year.FIRST },
	{ label: "Second Year", value: Year.SECOND },
	{ label: "Third Year", value: Year.THIRD },
	{ label: "Fourth Year", value: Year.FOURTH },
	{ label: "Fifth Year", value: Year.FIFTH },
	{ label: "Final Year", value: Year.FINAL },
];
const semesters = [
	{ label: "1st Semester", value: Semester.first_semester },
	{ label: "2nd Semester", value: Semester.second_semester },
];

const departmentNames = ["CEIT", "CIVIL", "MP", "EP", "EC"];

export const days = [
	{ label: "1", value: "1" },
	{ label: "2", value: "2" },
	{ label: "3", value: "3" },
	{ label: "4", value: "4" },
	{ label: "5", value: "5" },
	{ label: "6", value: "6" },
	{ label: "7", value: "7" },
	{ label: "8", value: "8" },
	{ label: "9", value: "9" },
	{ label: "10", value: "10" },
	{ label: "11", value: "11" },
	{ label: "12", value: "12" },
	{ label: "13", value: "13" },
	{ label: "14", value: "14" },
	{ label: "15", value: "15" },
	{ label: "16", value: "16" },
	{ label: "17", value: "17" },
	{ label: "18", value: "18" },
	{ label: "19", value: "19" },
	{ label: "20", value: "20" },
	{ label: "21", value: "21" },
	{ label: "22", value: "22" },
	{ label: "23", value: "23" },
	{ label: "24", value: "24" },
	{ label: "25", value: "25" },
	{ label: "26", value: "26" },
	{ label: "27", value: "27" },
	{ label: "28", value: "28" },
	{ label: "29", value: "29" },
	{ label: "30", value: "30" },
	{ label: "31", value: "31" },
];

export const months = [
	{ label: "January", value: "January" },
	{ label: "February", value: "February" },
	{ label: "March", value: "March" },
	{ label: "April", value: "April" },
	{ label: "May", value: "May" },
	{ label: "June", value: "June" },
	{ label: "July", value: "July" },
	{ label: "August", value: "August" },
	{ label: "September", value: "September" },
	{ label: "October", value: "October" },
	{ label: "November", value: "November" },
	{ label: "December", value: "December" },
];

export const times = [
	{ label: "0", value: "0" },
	{ label: "1", value: "1" },
	{ label: "2", value: "2" },
	{ label: "3", value: "3" },
	{ label: "4", value: "4" },
	{ label: "5", value: "5" },
	{ label: "6", value: "6" },
	{ label: "7", value: "7" },
];

export const totalTimes = [
	{ label: "1", value: "1" },
	{ label: "2", value: "2" },
	{ label: "3", value: "3" },
	{ label: "4", value: "4" },
	{ label: "5", value: "5" },
	{ label: "6", value: "6" },
	{ label: "7", value: "7" },
];
const TEACHERS: Teacher[] = [
	{
		id: "1",
		name: "Jhon Doe",
		username: "john123",
		email: "john@email.com",
		gender: "Male",
		department: "IT",
		position: "HOD",
		dateOfBirth: "19/1/1992",
		phone: "+1-234-567-8900",
	},
	{
		id: "2",
		name: "Cody Fisher",
		username: "codyfisher001",
		email: "cody.fisher@email.com",
		gender: "Female",
		department: "CEIT ",
		position: "Teacher",
		dateOfBirth: "15/5/1988",
		phone: "+1-234-567-8901",
	},
	{
		id: "3",
		name: "Sarah Smith",
		username: "sarah.smith",
		email: "sarah@email.com",
		gender: "Female",
		department: "IT",
		position: "Teacher",
		dateOfBirth: "22/8/1990",
		phone: "+1-234-567-8902",
	},
	{
		id: "4",
		name: "Sarah Smith",
		username: "sarah.smith",
		email: "sarah@email.com",
		gender: "Female",
		department: "IT",
		position: "Teacher",
		dateOfBirth: "22/8/1990",
		phone: "+1-234-567-8902",
	},
];

const STUDENTS: Student[] = [
	{
		id: "1",
		name: "Jhon Doe",
		student_id: "III-IT-1",
		email: "john@email.com",
		gender: "Male",
		department: "IT",
		semester: "First Semester",
		dateOfBirth: "19/1/1992",
		phone: "+1-234-567-8900",
	},
	{
		id: "2",
		name: "Jane Smith",
		student_id: "III-IT-2",
		email: "johnsmith@email.com",
		gender: "Male",
		department: "IT",
		semester: "First Semester",
		dateOfBirth: "19/1/2003",
		phone: "+1-234-567-8900",
	},
	{
		id: "3",
		name: "Alice Johnson",
		student_id: "III-IT-4",
		email: "alice@email.com",
		gender: "Male",
		department: "IT",
		semester: "First Semester",
		dateOfBirth: "19/1/2000",
		phone: "+1-234-567-8900",
	},
	{
		id: "4",
		name: "Jhon Doe",
		student_id: "IV-IT-20",
		email: "john@email.com",
		gender: "Male",
		department: "IT",
		semester: "Second Semester",
		dateOfBirth: "19/1/2002",
		phone: "+1-234-567-8900",
	},
];

const SUBJECTS = [
	{
		id: "1",
		name: "Operating System",
		code: "IT-42033",
		year: "1",
		semester: "1",
		teacher_name: "John Doe",
	},
	{
		id: "2",
		name: "Data Structure",
		code: "IT-42034",
		year: "1",
		semester: "2",
		teacher_name: "Jane Smith",
	},
	{
		id: "3",
		name: "Database Management System",
		code: "IT-42035",
		year: "2",
		semester: "1",
		teacher_name: "Alice Johnson",
	},
	{
		id: "4",
		name: "Computer Networks",
		code: "IT-42036",
		year: "2",
		semester: "2",
		teacher_name: "Bob Brown",
	},
	{
		id: "5",
		name: "Javascript",
		code: "IT-42038",
		year: "2",
		semester: "2",
		teacher_name: "Bob Brown",
	},
	{
		id: "6",
		name: "English",
		code: "E-42138",
		year: "2",
		semester: "2",
		teacher_name: "Bob Brown",
	},
	{
		id: "7",
		name: "Mathematics",
		code: "EM-41038",
		year: "2",
		semester: "2",
		teacher_name: "Bob Brown",
	},
];

const teacher_name_for_form_select = [
	{ label: "John Doe", value: "John Doe" },
	{ label: "Jane Smith", value: "Jane Smith" },
	{ label: "Alice Johnson", value: "Alice Johnson" },
	{ label: "Bob Brown", value: "Bob Brown" },
];

const attendanceReportData = [
	{
		no: 1,
		rollNo: "IV IT-1",
		name: "Ma Hla Hla",
		december: { times: 600, percentage: "94%" },
		january: { times: 580, percentage: "91%" },
		february: { times: 590, percentage: "93%" },
		march: { times: 610, percentage: "95%" },
	},
	{
		no: 2,
		rollNo: "IV IT-2",
		name: "Aung Aung",
		december: { times: 570, percentage: "90%" },
		january: { times: 560, percentage: "88%" },
		february: { times: 575, percentage: "91%" },
		march: { times: 585, percentage: "92%" },
	},
	{
		no: 3,
		rollNo: "IV IT-3",
		name: "Su Su Khin",
		december: { times: 620, percentage: "97%" },
		january: { times: 610, percentage: "96%" },
		february: { times: 615, percentage: "96%" },
		march: { times: 625, percentage: "98%" },
	},
	{
		no: 4,
		rollNo: "IV IT-4",
		name: "Kyaw Kyaw",
		december: { times: 540, percentage: "85%" },
		january: { times: 550, percentage: "87%" },
		february: { times: 560, percentage: "88%" },
		march: { times: 570, percentage: "90%" },
	},
	{
		no: 5,
		rollNo: "IV IT-5",
		name: "Hnin Ei Phyu",
		december: { times: 595, percentage: "93%" },
		january: { times: 600, percentage: "94%" },
		february: { times: 605, percentage: "95%" },
		march: { times: 610, percentage: "96%" },
	},
	{
		no: 6,
		rollNo: "IV IT-6",
		name: "Zaw Zaw",
		december: { times: 560, percentage: "88%" },
		january: { times: 570, percentage: "89%" },
		february: { times: 580, percentage: "91%" },
		march: { times: 590, percentage: "93%" },
	},
	{
		no: 7,
		rollNo: "IV IT-7",
		name: "May Myat Noe",
		december: { times: 630, percentage: "99%" },
		january: { times: 620, percentage: "97%" },
		february: { times: 625, percentage: "98%" },
		march: { times: 635, percentage: "99%" },
	},
	{
		no: 8,
		rollNo: "IV IT-8",
		name: "Min Min Oo",
		december: { times: 550, percentage: "86%" },
		january: { times: 560, percentage: "88%" },
		february: { times: 570, percentage: "90%" },
		march: { times: 580, percentage: "91%" },
	},
	{
		no: 9,
		rollNo: "IV IT-9",
		name: "Ei Ei Mon",
		december: { times: 605, percentage: "95%" },
		january: { times: 600, percentage: "94%" },
		february: { times: 610, percentage: "96%" },
		march: { times: 615, percentage: "97%" },
	},
	{
		no: 10,
		rollNo: "IV IT-10",
		name: "Phone Thant",
		december: { times: 580, percentage: "91%" },
		january: { times: 590, percentage: "93%" },
		february: { times: 600, percentage: "94%" },
		march: { times: 605, percentage: "95%" },
	},
];
const attendanceClassData = [
	{
		no: 1,
		rollNo: "IV IT-1",
		name: "Ma Hla Hla",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 2,
		rollNo: "IV IT-2",
		name: "Aung Aung",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 3,
		rollNo: "IV IT-3",
		name: "Su Su Khin",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 4,
		rollNo: "IV IT-4",
		name: "Kyaw Kyaw",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 5,
		rollNo: "IV IT-5",
		name: "Hnin Ei Phyu",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 6,
		rollNo: "IV IT-6",
		name: "Zaw Zaw",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 7,
		rollNo: "IV IT-7",
		name: "May Myat Noe",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 8,
		rollNo: "IV IT-8",
		name: "Min Min Oo",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 9,
		rollNo: "IV IT-9",
		name: "Ei Ei Mon",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
	{
		no: 10,
		rollNo: "IV IT-10",
		name: "Phone Thant",
		english: { present: 12, absent: "0" },
		Mathematics: { present: 12, absent: "0" },
		Java: { present: 12, absent: "0" },
		data_science: { present: 12, absent: "0" },
		computer_network: { present: 12, absent: 0 },
		dbms: { present: 12, absent: 0 },
		javascript: { present: 12, absent: 0 },
	},
];

export {
	genders,
	departments,
	roles,
	Years,
	semesters,
	departmentNames,
	TEACHERS,
	STUDENTS,
	SUBJECTS,
	teacher_name_for_form_select,
	attendanceReportData,
	attendanceClassData,
};
